version: '3'
services:
  ssl:
    build: ./
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./ssl-conf/httpd/ssl.conf:/etc/httpd/conf.d/ssl.conf
    container_name: 'ssl'
    tty: true
    privileged: true
    command: /sbin/init
